#!/bin/bash
git submodule init
git submodule update

# clean
rm -rf www_android

# lawnchair build first.
cd libs/lawnchair
./build dom
mv lc_prod.js ../../www/scripts/lawnchair.js

# xui build next.
cd ../xui
git submodule init
git submodule update
./build --minify
mv lib/xui-2.0.0.min.js ../../www/scripts/xui.js

# move xui plugin into www
cd ../..
cp libs/xui-plugins/fx-helpers/fx-helpers.js www/scripts/fx-helpers.js

# generate phonegap-android project
droidgap create /Users/filmaj/src/BeerMe/www